// Code generated by go-bindata.
// sources:
// static/build/base.css
// static/build/bootstrap.min.css
// static/build/favicon.png
// static/build/glyphicons-halflings-regular.eot
// static/build/glyphicons-halflings-regular.svg
// static/build/glyphicons-halflings-regular.ttf
// static/build/glyphicons-halflings-regular.woff
// static/build/glyphicons-halflings-regular.woff2
// static/build/index.html
// static/build/main.js
// static/build/main.js.map
// static/build/nsq_blue.png
// static/build/vendor.js
// DO NOT EDIT!

package nsqadmin

import (
	"fmt"
	"io/ioutil"
	"strings"
	"os"
	"path/filepath"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// baseCss reads file data from disk. It returns an error on failure.
func baseCss() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/base.css"
	name := "base.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bootstrapMinCss reads file data from disk. It returns an error on failure.
func bootstrapMinCss() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/bootstrap.min.css"
	name := "bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconPng reads file data from disk. It returns an error on failure.
func faviconPng() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/favicon.png"
	name := "favicon.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// glyphiconsHalflingsRegularEot reads file data from disk. It returns an error on failure.
func glyphiconsHalflingsRegularEot() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/glyphicons-halflings-regular.eot"
	name := "glyphicons-halflings-regular.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// glyphiconsHalflingsRegularSvg reads file data from disk. It returns an error on failure.
func glyphiconsHalflingsRegularSvg() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/glyphicons-halflings-regular.svg"
	name := "glyphicons-halflings-regular.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// glyphiconsHalflingsRegularTtf reads file data from disk. It returns an error on failure.
func glyphiconsHalflingsRegularTtf() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/glyphicons-halflings-regular.ttf"
	name := "glyphicons-halflings-regular.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// glyphiconsHalflingsRegularWoff reads file data from disk. It returns an error on failure.
func glyphiconsHalflingsRegularWoff() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/glyphicons-halflings-regular.woff"
	name := "glyphicons-halflings-regular.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// glyphiconsHalflingsRegularWoff2 reads file data from disk. It returns an error on failure.
func glyphiconsHalflingsRegularWoff2() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/glyphicons-halflings-regular.woff2"
	name := "glyphicons-halflings-regular.woff2"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// indexHtml reads file data from disk. It returns an error on failure.
func indexHtml() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/index.html"
	name := "index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// mainJs reads file data from disk. It returns an error on failure.
func mainJs() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/main.js"
	name := "main.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// mainJsMap reads file data from disk. It returns an error on failure.
func mainJsMap() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/main.js.map"
	name := "main.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// nsq_bluePng reads file data from disk. It returns an error on failure.
func nsq_bluePng() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/nsq_blue.png"
	name := "nsq_blue.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// vendorJs reads file data from disk. It returns an error on failure.
func vendorJs() (*asset, error) {
	path := "/Users/kpurdon/projects/nsq/nsqadmin/static/build/vendor.js"
	name := "vendor.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"base.css": baseCss,
	"bootstrap.min.css": bootstrapMinCss,
	"favicon.png": faviconPng,
	"glyphicons-halflings-regular.eot": glyphiconsHalflingsRegularEot,
	"glyphicons-halflings-regular.svg": glyphiconsHalflingsRegularSvg,
	"glyphicons-halflings-regular.ttf": glyphiconsHalflingsRegularTtf,
	"glyphicons-halflings-regular.woff": glyphiconsHalflingsRegularWoff,
	"glyphicons-halflings-regular.woff2": glyphiconsHalflingsRegularWoff2,
	"index.html": indexHtml,
	"main.js": mainJs,
	"main.js.map": mainJsMap,
	"nsq_blue.png": nsq_bluePng,
	"vendor.js": vendorJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"base.css": &bintree{baseCss, map[string]*bintree{
	}},
	"bootstrap.min.css": &bintree{bootstrapMinCss, map[string]*bintree{
	}},
	"favicon.png": &bintree{faviconPng, map[string]*bintree{
	}},
	"glyphicons-halflings-regular.eot": &bintree{glyphiconsHalflingsRegularEot, map[string]*bintree{
	}},
	"glyphicons-halflings-regular.svg": &bintree{glyphiconsHalflingsRegularSvg, map[string]*bintree{
	}},
	"glyphicons-halflings-regular.ttf": &bintree{glyphiconsHalflingsRegularTtf, map[string]*bintree{
	}},
	"glyphicons-halflings-regular.woff": &bintree{glyphiconsHalflingsRegularWoff, map[string]*bintree{
	}},
	"glyphicons-halflings-regular.woff2": &bintree{glyphiconsHalflingsRegularWoff2, map[string]*bintree{
	}},
	"index.html": &bintree{indexHtml, map[string]*bintree{
	}},
	"main.js": &bintree{mainJs, map[string]*bintree{
	}},
	"main.js.map": &bintree{mainJsMap, map[string]*bintree{
	}},
	"nsq_blue.png": &bintree{nsq_bluePng, map[string]*bintree{
	}},
	"vendor.js": &bintree{vendorJs, map[string]*bintree{
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

